# Imagen base de PHP con soporte para FPM (PHP 8.2)
FROM php:8.2-fpm

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y \
    libzip-dev \
    unzip \
    git \
    curl \
    && docker-php-ext-install pdo pdo_mysql zip

# Instalar Composer
COPY --from=composer:2.5 /usr/bin/composer /usr/bin/composer
RUN chmod -R 775 storage bootstrap/cache

# Copiar los archivos del proyecto Laravel al contenedor
COPY . /var/www/html

# Configurar el directorio de trabajo
WORKDIR /var/www/html

RUN composer install --no-dev --optimize-autoloader

# Dar permisos a los directorios de almacenamiento y caché
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache

# Exponer el puerto 8000, ya que usaremos `php artisan serve`
EXPOSE 8080
CMD php artisan serve --host=0.0.0.0 --port=8080
